---
title: "bootstrap"
author: "Wenjie Wu"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(p8105.datasets)

set.seed(1)
```

do some bootstrapping

make some data

```{r}
n_samp = 250

sim_df_constant = 
  tibble(
    x = rnorm(n_samp, 1, 1),
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3 * x + error
  )

sim_df_nonconstant = 
  sim_df_constant |>
  mutate(
    error = error * .75 * x,
    y = 2 + 3 * x + error
  )
```

```{r}
sim_df_constant |>
  ggplot(aes(x = x, y = y)) +
  geom_point() +
  stat_smooth(method = "lm")
```

Look at regression results

```{r}
sim_df_constant |>
  lm(y ~ x, data = _) |>
  broom::tidy() |>
  knitr::kable(digits = 3)
```

##mDraw a bootstrap sample

```{r}
boot_sample = function(df){
  
  boot_df = 
    sample_frac(df, replace = TRUE)
  
  return(boot_df)
}
```

```{r}
sim_df_nonconstant |>
  boot_sample() |>
  ggplot(aes(x = x, y = y)) +
  geom_point(alpha = .5) +
  stat_smooth(method = "lm")
```

```{r}
sim_df_nonconstant |>
  boot_sample() |>
  lm(y ~ x, data = _) |>
  broom::tidy() |>
  knitr::kable(digits = 3)
```

## bootstrap a lot

```{r}
boot_straps = 
  tibble(
    strap_number = 1:1000
  ) |>
  mutate(
    strap_sample = map(strap_number, \(i) boot_sample(df = sim_df_nonconstant)),
    models = map(strap_sample, \(df) lm(y ~ x, data = df)),
    results = map(models, broom::tidy)
  )

bootstraps_results =
  boot_straps |>
  select(strap_number, results) |>
  unnest(results) |>
  group_by(term) |>
  summarize(
    boot_se = sd(estimate)
  ) |>
  knitr::kable()
```

## do this all using modelr

```{r}
boot_straps = 
  sim_df_constant |>
  modelr::bootstrap(1000) |>
  mutate(
    strap = map(strap, as_tibble),
    models = map(strap, \(df) lm(y ~ x, data = df)),
    results = map(models, broom::tidy)
  ) |>
  select(.id, results) |>
  unnest(results)
```

report

```{r}
boot_straps |>
  group_by(term) |>
  summarize(
    boot_est = mean(estimate),
    boot_se = sd(estimate),
    boot_ci_ll = quantile(estimate, .025),
    boot_ci_ul = quantile(estimate, .975)
  )
```

## Airbnb

```{r}
data("nyc_airbnb")

manhattan_df = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough == "Manhattan") |> 
  select(price, stars, room_type) |>
  drop_na()
```

```{r}
manhattan_df |>
  ggplot(aes(x = stars, y = price)) +
  geom_point() +
  stat_smooth(method = "lm", se = FALSE)
```

fit a regression

```{r}
manhattan_df |>
  lm(price ~ stars, data = _) |>
  broom::tidy() |>
  knitr::kable(digits = 3)
```

```{r}
boots_results = 
  manhattan_df |>
  modelr::bootstrap(10) |>
  mutate(
    strap = map(strap, as_tibble),
    models = map(strap, \(df) lm(price ~ stars + room_type, data = df)),
    results = map(models, broom::tidy)
  ) |>
  select(.id, results) |>
  unnest(results)

boots_results |>
  filter(term == "stars") |>
  ggplot(aes(estimate)) +
  geom_density()

boots_results |>
  group_by(term) |>
  summarize(
  boot_est = mean(estimate),
  boot_se = sd(estimate),
  boot_ci_ll = quantile(estimate, .025),
  boot_ci_ul = quantile(estimate, .975)
  )
```


